apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-utkast-frontend
  namespace: min-side
  labels:
    team: min-side
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /minside/utkast/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /minside/utkast/api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /minside/utkast/metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      rules:
        - application: tms-utkast
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
    - "https://www.nav.no/minside/utkast"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: UTKAST_API_URL
      value: "http://tms-utkast/v2/utkast"
    - name: MIN_SIDE_URL
      value: "https://www.nav.no/minside/"
    - name: REDIRECT_URI
      value: "https://www.nav.no/minside/utkast"