name: "Deploy main"
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: "Build application"
        run: "npm run build"

      - name: "Upload to cdn"
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: min-side
          source: ./dist/client/_astro
          destination: 'tms-utkast-frontend'
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: "Build and push"
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: min-side
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    runs-on: "ubuntu-latest"
    needs: "build"
    strategy:
      matrix:
        cluster: [ dev-gcp, prod-gcp ]
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/${{ matrix.cluster }}/nais.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
