name: "Deploy main"
on:
  push:
    branches:
      - "main"

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  build-and-deploy:
    uses: navikt/tms-deploy/.github/workflows/astro-deploy-v1.yaml@v1
    with:
      app-name: "tms-utkast-frontend"
      clusters: '["dev-gcp", "prod-gcp"]'
    secrets: inherit
