name: "Deploy main"
on:
  push:
    branches:
      - "main"

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  build-and-deploy:
    uses: navikt/tms-deploy/.github/workflows/astro-deploy-v1.yaml@main
    with:
      app-name: "tms-utkast-frontend"
      clusters: '["dev-gcp", "prod-gcp"]'
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      ASTRO_KEY: ${{ secrets.ASTRO_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
